### ISSUE TITLE
Implementar rota para consulta de ofertas de módulos vinculadas à pessoa supervisora

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/sagu-api#3]
# Objetivo

**Eu como** como pessoa supervisora  
**Quero** consultar as ofertas de módulos na qual estão vinculadas ao meu perfil  
**Para que** eu posso tomar alguma ação sobre as ofertas de módulos  

# Contexto
## O que originou

O desenvolvimento de um módulo de pessoa supervisora no sistema do SAGU consistirá de uma nova interface para a pessoa usuária Supervisora. 
Sendo assim, esta pessoa quando autenticada precisará consultar as suas ofertas de módulo.

## Qual solução proposta

Criar uma rota que irá retornar as ofertas de módulo para os dados de pessoa usuária definida token JWT enviado no cabeçalho. Adicionar a possibilidade de paginação de 25 em 25, passando o parâmetro page, com o número da página.

A rota a ser criada será: `/supervisores/turma/{turma}/ofertas/{page?}`

# Fora de Contexto

Cadastro, atualização e remoção de ofertas de módulo.

# Critérios de aceitação

- [x] **Dado que** sou uma pessoa usuária autenticada  
**Quando** enviar uma requisição `GET`, sem atributo page  
**Então** retornar as primeiras 25 ofertas de módulo para o TOKEN enviado

- [x] **Dado que** sou uma pessoa usuária autenticada  
**Quando** enviar uma requisição `GET`, com o page, `número inteiro`  
**Então** retornar as 25 ofertas de módulo correspondente a página, (25 * page), para o TOKEN enviado

- [x] **Dado que** sou uma pessoa usuária autenticada  
**Quando** enviar uma requisição `GET`, com o page, que não seja um `número inteiro`  
**Então** retornar uma mensagem de erro com o status `400` informando que o valor é inválido para a página.

# Observações

- EPIC;  https://github.com/EscolaDeSaudePublica/sagu/issues/28

**Comment by victorMagalhaesPacheco** [comment]
**Atualizações necessárias**

- Necessário retornar no json a carga horária lançada para cada tipo `Prática`, `Teórico-conceitual (ead+presencial)` e `Teórico-prática (campo+núcleo)`
