### ISSUE TITLE
Adicionar propriedade no retorno de fotos dos residentes da resmulti

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/sagu-api#35]
# Objetivo

**Eu como**  cliente de consumo da API 
**Quero** consultar os residentes matriculados com uma propriedade de foto 
**Para que** possa ser apresentado no cliente a foto do residente que está sendo gerenciado

# Contexto

## O que originou

Ao desenvolver a funcionalidade de lançamento de gerenciamento de residente da residência multiprofissional, constatou-se a necessidade mapear as fotos previamente cadastradas dos residentes.

## Qual solução proposta

Adicionar uma nova propriedade de retorno da foto contendo o link de acesso da imagem

# Fora de Contexto

Cadastrar novas imagens

**Comment by victorMagalhaesPacheco** [comment]
Para realizar o acesso externo das fotos dos residentes via API é necessário liberar a permissão dentro do SAGU no arquivo `miolo20/modules/basic/handlers/getfile.inc`.

**Comment by victorMagalhaesPacheco** [comment]
@ericsonmoreira para acesso ao retorno da imagem, é necessário 
- Atualizar o sagu local da branch `residencia_multiprofissional` 
- Realizar a permissão ao diretório de `sagu/miolo20/modules/basic/upload` para que possa ser enviado as imagens no cadastro da pessoa. 
- O ultimo passo é adicionar dentro da API no arquivo .env a URL do SAGU `SAGU_URL=http://localhost:81/`.

**Comment by ericsonmoreira** [comment]
@victorMagalhaesPacheco Fiz essas mudanças.
