### ISSUE TITLE
Implementar/ajustar API no Sagu para disponibilizar os critérios/status de aprovação/reprovação para outros sistemas

### ISSUE THREAD

**Issue by ricardopoppi** [EscolaDeSaudePublica/sagu-api#39]
**URL do calendário/Data/Local**: _apagar_a_linha_se_não_houver_

# Contextualização

## O que originou

Dado a [demanda de uma integração](https://github.com/EscolaDeSaudePublica/FeliciLab/issues/307) do sistema Sagu com o sistema Mapa digital da Saúde, que solicita adicionar dentro do sistema Sagu os candidatos/agente selecionados de um determinado curso dentro do Mapa digital da Saúde. Para que não haja o retrabalho de cadastrar cada candidato dentro do Sagu e adiciona-lo a uma determinada turma dentro do Sagu .

## 🚀 Objetivos

**Eu como** desenvolvedor do sagu
**Quero** desenvolver na api do sagu, caso já não haja, a possibilidade de expor informações de turmas ou cursos
**Para** outros sistema consumirem esse endpoint

**Eu como** desenvolvedor do sagu
**Preciso** saber quais informações de quais dados como curso, unidade temática, turma ou outros dados vai precisar
**Para** outros sistema consumirem esse endpoint

## Critérios de aceitação

- [ ] Acessar um endpoint passando parametros e recebendo um json com informações desejadas.

# Resultados

Entrega de resultado é outros sistemas receberem informações do sistema Sagu

**Comment by ricardopoppi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/sagu-api/39?planning-poker) with ZenHub @victorMagalhaesPacheco @Junior-Shyko @ericsonmoreira @jeff-doliveira1

**Comment by JuinEsp** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Integraes-de-Produtos-622f81f2eaf7c70010bd1495/issues/EscolaDeSaudePublica/sagu-api/39?planning-poker) with ZenHub @JuinEsp

**Comment by ricardopoppi** [comment]
Essa issue está deprecada porque a arquitetura da história mudou
