### ISSUE TITLE
Implementar rota para realizar lançamento de faltas

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/sagu-api#4]
# Objetivo

**Eu como** pessoa supervisora  
**Quero** lançar faltas para uma pessoa residente  
**Para que** sua nota de assiduidade de possa ser computada corretamente  

# Contexto

## O que originou

O desenvolvimento de um módulo de pessoa supervisora no sistema do SAGU consistirá de uma nova interface para a pessoa usuária Supervisora.
Sendo assim, esta pessoa quando autenticada precisará lançar faltas para uma determinada residente.

## Qual solução proposta

Desenvolver uma rota na qual a pessoa supervisora poderá registrar uma quantidade de falta para uma determinada pessoa residente, definido na rota:  
`/residencia-multiprofissional/supervisores/turma/{turma}/oferta/{oferta}/residente/{id}/faltas/{faltas}`

# Fora de Contexto

- Efetuar qualquer alteração além da falta

# Critérios de aceitação

- [x] **Dado que** estou enviando uma requisição para registrar falta  
**Quando** envio uma requisição com uma determinada quantidade de faltas  
**Então** retornar uma mensagem de registro de que as faltas foram salva com sucesso, status `200`

- [x] **Dado que** estou enviando uma requisição para registrar falta  
**Quando** envio uma oferta de módulo inexistente
**Então** retornar uma mensagem de erro informando oferta não encontrada, status `400`

# Observações

- EPIC: https://github.com/EscolaDeSaudePublica/sagu/issues/28

**Comment by victorMagalhaesPacheco** [comment]
**Atualizações necessárias**

- Necessário armazenar dados no schema `res` na tabela `ofertadeunidadetematicafaltadoresidente`
- Necessário ser possível cadastrar e atualizar as faltas para os tipos `Prática`, `Teórico-conceitual (ead+presencial)` e `Teórico-prática (campo+núcleo)`
- Mudar o verbo http da rota de `GET` para `POST` ou `PUT`

**Comment by victorMagalhaesPacheco** [comment]
Na análise realizada para a funcionalidade de lançamento de faltas, verificou-se que o lançamento é feito exclusivamente para as ofertas transversais, ou seja, ofertas específicas não entram no lançamento, mas na consulta recebem os mesmos valores da oferta pai (transversal).

**Comment by victorMagalhaesPacheco** [comment]
**Especificação do endpoint**

**Endpoint**: `/residencia-multiprofissional/supervisores/turma/TURMA_ID/oferta/OFERTA_ID/faltas`
**Verbo HTTP**: `POST`
**Headers**: 
`
Authorization: Bearer _TOKEN_
`
`
Content-Type: application/json
`
**Data JSON**:
```javascript
{
   "faltas":[
      {
         "residenteid":"1",
         "falta":"50",
         "tipo":"P",
         "observacao":"Faltou por motivo X"
      },
      {
         "residenteid":"1",
         "falta":"50",
         "tipo":"C",
         "observacao":"Faltou por motivo Y"
      },
      {
         "residenteid":"1",
         "falta":"0",
         "tipo":"T",
         "observacao":"Faltou por motivo Y"
      }
   ]
}
```
