### ISSUE TITLE
Implementar rota para realizar lançamento de notas

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/sagu-api#5]
# Objetivo

**Eu como** pessoa supervisora  
**Quero** lançar notas para uma pessoa residente  
**Para que** sua nota possa ser computada corretamente  

# Contexto

## O que originou

O desenvolvimento de um módulo de pessoa supervisora no sistema do SAGU consistirá de uma nova interface para a pessoa usuária Supervisora.
Sendo assim, esta pessoa quando autenticada precisará lançar as notas para uma determinada residente.

## Qual solução proposta

Desenvolver uma rota na qual a pessoa supervisora poderá registrar uma quantidade de falta para uma determinada pessoa residente, definido na rota:  
`/residencia-multiprofissional/supervisores/turma/TURMA_ID/oferta/OFERTA_ID/notas`

# Fora de Contexto

- Efetuar qualquer alteração além da nota

# Critérios de aceitação

- [x] **Dado que** estou enviando uma requisição para registrar a nota  
**Quando** envio uma requisição com os valores corretos para cada nota
**Então** retornar uma mensagem de registro de a nota foi salva com sucesso, status `200`

- [x] **Dado que** estou enviando uma requisição para registrar a nota  
**Quando** envio uma requisição sem enviar a nota pratica ou teórica  
**Então** retornar uma mensagem de erro ao registrar a nota, status `400`

- [x] **Dado que** estou enviando uma requisição para registrar a nota  
**Quando** envio uma requisição com alguma nota menor que 0 e maior que 10  
**Então** retornar uma mensagem de erro ao registrar a nota, status `400`

- [x] **Dado que** estou enviando uma requisição para registrar a nota  
**Quando** envio uma requisição com alguma nota com caracteres não numéricos, exceto o ponto `.`  
**Então** retornar uma mensagem de erro ao registrar a nota, status `400`

- [x] **Dado que** estou enviando uma requisição para registrar a nota  
**Quando** envio uma requisição com alguma nota com mais de 1 ponto  
**Então** retornar uma mensagem de erro ao registrar a nota, status `400`

- [x] **Dado que** estou enviando uma requisição para registrar nota    
**Quando** envio uma oferta de módulo inexistente
**Então** retornar uma mensagem de erro informando oferta não encontrada, status `400`

# Observações

- EPIC: https://github.com/EscolaDeSaudePublica/sagu/issues/28

**Comment by victorMagalhaesPacheco** [comment]
**Atualizações necessárias**

- Necessário armazenar dados no schema `res` na tabela `ofertadeunidadetematicanotas`
- Necessário ser possível cadastrar e atualizar as notas para os tipos `Nota atividade de produto`, `Nota de avaliação de desempenho`
- Mudar o verbo http da rota de `GET` para `POST` ou `PUT`

**Comment by victorMagalhaesPacheco** [comment]
**Especificação do endpoint**

@ericsonmoreira 

**Endpoint**: `/residencia-multiprofissional/supervisores/turma/TURMA_ID/oferta/OFERTA_ID/notas`
**Verbo HTTP**: `POST`
**Headers**: 
`
Authorization: Bearer _TOKEN_
`
`
Content-Type: application/json
`
**Data JSON**:
```javascript
{
   "notas":[
      {
         "residenteid": 1,
         "notadeatividadedeproduto": 10,
         "notadeavaliacaodedesempenho": 8
      },
      {
         "residenteid": 2,
         "notadeatividadedeproduto": 6,
         "notadeavaliacaodedesempenho": 7
      },
   ]
}
```
