### ISSUE TITLE
Implementar rota para realizar lançamento de carga horária complementar

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/sagu-api#6]
# Objetivo

**Eu como** pessoa supervisora  
**Quero** lançar carga horária complementar para uma pessoa residente  
**Para que** sua nota possa ser computada corretamente  

# Contexto

## O que originou

O desenvolvimento de um módulo de pessoa supervisora no sistema do SAGU consistirá de uma nova interface para a pessoa usuária Supervisora.
Sendo assim, esta pessoa quando autenticada precisará lançar a carga horária complementar para uma determinada residente.

## Qual solução proposta

Desenvolver uma rota na qual a pessoa supervisora poderá registrar uma quantidade de falta para uma determinada pessoa residente, definido na rota:  
`residencia-multiprofissional/supervisores/turma/{turma}/orferta/{oferta_modulo}/residente/{id}/carga-horaria-complementar/{cargaHoraria}`

# Fora de Contexto

- Efetuar qualquer alteração além da carga horária complementar

# Critérios de aceitação

- [ ] **Dado que** estou enviando uma requisição para registrar a carga horária complementar  
**Quando** envio uma requisição com um determinado valor de carga horária complementar  
**Então** retornar uma mensagem de registro de que a carga horária complementar foi salva com sucesso, status `200`

- [ ] **Dado que** estou enviando uma requisição para registrar a carga horária complementar  
**Quando** envio uma requisição sem enviar a carga horária complementar  
**Então** retornar uma mensagem de erro ao registrar a carga horária complementar, status `400`

- [ ] **Dado que** estou enviando uma requisição para registrar a carga horária complementar  
**Quando** envio uma requisição sem enviar a carga horária complementar  
**Então** retornar uma mensagem de erro ao registrar a carga horária complementar, status `400`

- [ ] **Dado que** estou enviando uma requisição para registrar a carga horária complementar  
**Quando** envio uma requisição com uma carga horária complementar menor que 0  
**Então** retornar uma mensagem de erro ao registrar a nota, status `400`

- [ ] **Dado que** estou enviando uma requisição para registrar carga horária complementar    
**Quando** envio uma oferta de módulo inexistente
**Então** retornar uma mensagem de erro informando oferta não encontrada, status `400`

- [ ] **Dado que** estou enviando uma requisição para registrar carga horária complementar  
**Quando** envio 3 digitos de CPF que não correspondem ao ID da pessoa residente
**Então** retornar uma mensagem de erro informando falhou o registro da nota, status `400`

# Observações

- EPIC: https://github.com/EscolaDeSaudePublica/sagu/issues/28

**Comment by victorMagalhaesPacheco** [comment]
Atividade bloqueada devido a migração do responsável técnico para outro projeto.
