### ISSUE TITLE
Implementar rota para consulta de residentes matriculados em uma oferta de módulo

### ISSUE THREAD

**Issue by oxechicao** [EscolaDeSaudePublica/sagu-api#8]
# Objetivo

**Eu como** como pessoa supervisora  
**Quero** consultar as pessoas residentes para uma oferta de módulo na instituição executora que sou responsável
**Para que** eu posso tomar alguma ação sob as pessoas residentes ofertas de módulos  

# Contexto

## O que originou

O desenvolvimento de um módulo de pessoa supervisora no sistema do SAGU consistirá de uma nova interface para a pessoa usuária Supervisora. 
Sendo assim, esta pessoa quando autenticada precisará consultar as suas ofertas de módulo.

A rota a ser criada será: `/residencia-multiprofissional/supervisores/turma/{turma}/oferta/{oferta}/residentes`
Rota para retornar 1 residente: `/residencia-multiprofissional/supervisores/turma/{turma}/oferta/{oferta}/residentes/{residenteId?}`

# Fora de Contexto

Cadastro, atualização e remoção de residentes.

# Critérios de aceitação

- [ ] **Dado que** sou uma pessoa usuária autenticada  
**Quando** enviar uma requisição `GET`, sem atributo page  
**Então** retornar os residentes

- [ ] **Dado que** sou uma pessoa usuária autenticada  
**Quando** enviar uma requisição `GET`, com o page, que não seja um `número inteiro`  
**Então** retornar uma mensagem de erro com o status `400` informando que o valor é inválido para a página.

# Observações

- EPIC;  https://github.com/EscolaDeSaudePublica/sagu/issues/28
**Atualização**

# Atualizações

Pontos importantes a atualizar verificado na reunião realizada no dia 25/06/2021 sobre a validação das funcionalidades de responsabilidade dos supervisor.

A pendência de carga horária deve ser baseado na porcentagem para cada tipo:

**- Prático: 0% de tolerância**
  Ex: 
  carga horária oferta: 100h
  carga horária falta: 20h
  carga horária pendente residente: 20h
  

**- Teórico prático: 15% de tolerância**
   Ex: 
  carga horária oferta: 100h
  carga horária falta: 20h
  carga horária pendente residente: 5h

**- Teórico conceitual: 15% de tolerância**
   Ex: 
  carga horária oferta: 100h
  carga horária falta: 20h
  carga horária pendente residente: 5h

**Comment by victorMagalhaesPacheco** [comment]
**Ajustes**

- Necessário adicionar campo instituição executora do residente
- Necessário retornar somente os residentes matriculados na oferta de atividade do módulo na instituição executora em que o supervisor é responsável

**Comment by victorMagalhaesPacheco** [comment]
**Ajustes**

- Necessário adicionar mais uma propriedade de retorno de faltas compiladas do residente matriculado

**Comment by victorMagalhaesPacheco** [comment]
**Atualização**

Pontos importantes a atualizar verificado na reunião realizada no dia 25/06/2021 sobre a validação das funcionalidades de responsabilidade dos supervisor.

A pendência de carga horária deve ser baseado na porcentagem para cada tipo:

Ex: Carga horária oferta: 300h (P, TC, TP)

**- Prático: 0% de tolerância**
  Ex: 
  carga horária oferta tipo P: 100h
  carga horária oferta mínima aprovação: 100h
  carga horária falta: 20h
  carga horária presente: 80h
  carga horária pendente residente para aprovação: 20h
  

**- Teórico prático: 15% de tolerância**
   Ex: 
  carga horária oferta tipo TP: 100h
  carga horária oferta mínima aprovação: 85h
  carga horária falta: 20h
  carga horária presente: 80h
  carga horária pendente residente para aprovação: 5h

**- Teórico conceitual: 15% de tolerância**
   Ex: 
  carga horária oferta tipo TC: 100h
  carga horária oferta mínima aprovação: 85h
  carga horária falta: 20h
  carga horária presente: 80h
  carga horária pendente residente para aprovação: 5h
